### ISSUE TITLE
twitch fails to show/play stream

### ISSUE THREAD

**Issue by javierdlr** [walkero-gr/aiostreams#8]
#KDH1:Comm/aiostreams/twitch.py -u https://www.twitch.tv/videos/2005030791
aiostreams vv1.7.6 (2022-12-04) - Developed by George Sokianos

Traceback (most recent call last):
File "KDH1:Comm/aiostreams/twitch.py", line 302, in <module>
main(sys.argv[1:])
File "KDH1:Comm/aiostreams/twitch.py", line 279, in main
videoInfo = aioapi.getVideoInfo(video['id'], video['type'])
File "KDH1:Comm/aiostreams/twitch.py", line 126, in getVideoInfo
return json.loads(responseData)
File "Utilidades:Comm/aiostreams/simplejson/__init__.py", line 518, in loads
return _default_decoder.decode(s)
File "Utilidades:Comm/aiostreams/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "Utilidades:Comm/aiostreams/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
File "Utilidades:Comm/aiostreams/simplejson/scanner.py", line 79, in scan_once
return _scan_once(string, idx)
File "Utilidades:Comm/aiostreams/simplejson/scanner.py", line 70, in _scan_once
raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
#

[https://aiostreams.amiga-projects.net/ ... /channel/429381908/videos](https://aiostreams.amiga-projects.net/twitch/channel/429381908/videos)

https://www.amigans.net/modules/newbb/viewtopic.php?post_id=145387#forumpost145387

**Comment by walkero-gr** [comment]
@javierdlr thank you so much for bringing this to my attention. This is fixed now.

**Comment by javierdlr** [comment]
Hi downloaded new version and I can't see twitch video stream:

#twitch.py -u https://www.twitch.tv/videos/2005030791
aiostreams vv1.7.7 (2023-12-20) - Developed by George Sokianos

Traceback (most recent call last):
File "twitch.py", line 302, in <module>
main(sys.argv[1:])
File "twitch.py", line 279, in main
videoInfo = aioapi.getVideoInfo(video['id'], video['type'])
File "twitch.py", line 124, in getVideoInfo
responseData = self.call(endpoint, query)
File "twitch.py", line 67, in call
return self.getURL(url)
File "twitch.py", line 57, in getURL
print (URLError["reason"])
TypeError: 'type' object is unsubscriptable
#


¿:-/

**Comment by walkero-gr** [comment]
@javierdlr this should work again. can you please let me know if it works for you?
